services:
  quant-backend:
    build: .
    image: quant-backend:local
    container_name: local-quant-node
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=local